### ISSUE TITLE
Reshaping error "shape '[32, -1, 112, 112]' is invalid for input of size 865536"

### ISSUE THREAD

**Issue by Agrawalchitranshu** [ahmetgunduz/Real-time-GesRec#53]
I am trying to do both detection and clasification for jster dataset and I have trained the detector part of it and saved it's checkpoint and for the classification part I am using the checkpoint that you have provided. So for inferencing pupose I am running run_online.sh file by putting both checkpoints there. So for that I have made Jester_online.py file just like you made egogesture_online.py to get the dataset to provide for evaluation but it is showing some reshape error in the following line -
clip = torch.cat(clip, 0).view((self.sample_duration, -1) + im_dim).permute(1, 0, 2, 3)
the error is - 
RuntimeError: shape '[32, -1, 112, 112]' is invalid for input of size 865536

For simple classification, I didn't get this error. I don't know where did this number 865536 come from.
Can you help me out with this problem. I am attaching the screenshot here.
![Screenshot from 2020-04-17 12-17-47](https://user-images.githubusercontent.com/21341582/79540405-bbfb7700-80a5-11ea-993d-c3ebfd4d6cc1.png)

**Comment by ahmetgunduz** [comment]
hi @Agrawalchitranshu , can you please check the `clip.shape`. It seems it is equal to 865536 which is not divisible by 32*112*112. This is only possible when the input data is not properly read or not reshaped into 112*112. Could you please share the Spatial Transformation you are applying?

**Comment by Agrawalchitranshu** [comment]
I am applying the same spatial transformation as you applied, nothing I have changed.
spatial_transform = Compose([
    Scale(112),
    CenterCrop(112),
    ToTensor(opt.norm_value), norm_method
    ])
This is the definition of the spatial transform and this is how i am calling this definition :-
if self.spatial_transform is not None:
    self.spatial_transform.randomize_parameters()
    clip = [self.spatial_transform(img) for img in clip]

This is same as you have provided.
I am also printing this -
im_dim = clip[0].size()[-2:]
print(im_dim)

And it is showning torch(112, 112).
And one more thing, when I am dividing the number 865536 by 112*112 then the Quotient that I am getting is 69 which is not divisible by 32(sample duration). I think the problem is in Quotient.
Please verify once more.
Thanks

**Comment by ahmetgunduz** [comment]
@Agrawalchitranshu  can you please confirm that your temporal transformation is the same as following?: 
https://github.com/ahmetgunduz/Real-time-GesRec/blob/31c2c7d026ee8971da5a6a5d4a01cf91bf670756/main.py#L107-L109

**Comment by Agrawalchitranshu** [comment]
Okay, I have defined the temporal_transform as same as you defined but most important thing is that I want to try to inference the model (detection + classification), so I am running run_online.sh script which directs to online_test.py script and in that same definition of temporal_transform is defined but while taking the data in line
"test_data = get_online_data(opt, spatial_transform, None, target_transform)"
Instead of applying temporal_transform, you have written 'None', which this is not the case in main.py.
Please help me understand this.
Thanks!

**Comment by ahmetgunduz** [comment]
I assume the issue above is solved? 

Regarding `None` in the online_test.py you must understand what temporal transform actually is. Temporal transformation is used to force the number of the input frames be equal to the `sample_duration`. Not all the video clips have equal number of frames. For example,  when you have a clip of size 69 frames as stated above you must select 32 of them and fed to the model. There are many ways to select 32 of them and temporal transformation does exactly this. You can either select 32 frames in the center of the clips, or select a random region of the clip. 

About your question, you are doing inference in real time. This means that you will have a sliding window of size 32. So you do not need to do a temporal selection since you are sliding a window of size 32 already. That is why it is None in online case. 

Hope this helps,
Ahmet

**Comment by Agrawalchitranshu** [comment]
Thanks, I understand this, I am eactly doing the same thing but why am I getting that error, that is my question, Do I have to apply temporal transformation compulsarily while inferencing? Because what I am seeing is even having a sliding window of 32 frames I am still getting that error.
What exactly should I do?

**Comment by ahmetgunduz** [comment]
Best shot would be do debugging in the dataset.py.

**Comment by Agrawalchitranshu** [comment]
Yeah, solved it, thanks!
